version: '3.8'
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  servidor:
    build: ./servidor
    container_name: servidor
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: